//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.LocalLotGenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalLotGenServiceReference.IWCF_LotteryGenService")]
    public interface IWCF_LotteryGenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_LotteryGenService/bigLottery", ReplyAction="http://tempuri.org/IWCF_LotteryGenService/bigLotteryResponse")]
        string bigLottery(int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_LotteryGenService/bigLottery", ReplyAction="http://tempuri.org/IWCF_LotteryGenService/bigLotteryResponse")]
        System.Threading.Tasks.Task<string> bigLotteryAsync(int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_LotteryGenService/powerLottery", ReplyAction="http://tempuri.org/IWCF_LotteryGenService/powerLotteryResponse")]
        string powerLottery(int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_LotteryGenService/powerLottery", ReplyAction="http://tempuri.org/IWCF_LotteryGenService/powerLotteryResponse")]
        System.Threading.Tasks.Task<string> powerLotteryAsync(int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_LotteryGenService/jintsai539", ReplyAction="http://tempuri.org/IWCF_LotteryGenService/jintsai539Response")]
        string jintsai539(int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_LotteryGenService/jintsai539", ReplyAction="http://tempuri.org/IWCF_LotteryGenService/jintsai539Response")]
        System.Threading.Tasks.Task<string> jintsai539Async(int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCF_LotteryGenServiceChannel : WebRole1.LocalLotGenServiceReference.IWCF_LotteryGenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCF_LotteryGenServiceClient : System.ServiceModel.ClientBase<WebRole1.LocalLotGenServiceReference.IWCF_LotteryGenService>, WebRole1.LocalLotGenServiceReference.IWCF_LotteryGenService {
        
        public WCF_LotteryGenServiceClient() {
        }
        
        public WCF_LotteryGenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCF_LotteryGenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_LotteryGenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_LotteryGenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string bigLottery(int quantity) {
            return base.Channel.bigLottery(quantity);
        }
        
        public System.Threading.Tasks.Task<string> bigLotteryAsync(int quantity) {
            return base.Channel.bigLotteryAsync(quantity);
        }
        
        public string powerLottery(int quantity) {
            return base.Channel.powerLottery(quantity);
        }
        
        public System.Threading.Tasks.Task<string> powerLotteryAsync(int quantity) {
            return base.Channel.powerLotteryAsync(quantity);
        }
        
        public string jintsai539(int quantity) {
            return base.Channel.jintsai539(quantity);
        }
        
        public System.Threading.Tasks.Task<string> jintsai539Async(int quantity) {
            return base.Channel.jintsai539Async(quantity);
        }
    }
}
