//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.cmdHelperServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cmdHelperServiceReference.IWCF_cmdHelpService")]
    public interface IWCF_cmdHelpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_cmdHelpService/CommandOutput", ReplyAction="http://tempuri.org/IWCF_cmdHelpService/CommandOutputResponse")]
        string CommandOutput(string commandText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCF_cmdHelpService/CommandOutput", ReplyAction="http://tempuri.org/IWCF_cmdHelpService/CommandOutputResponse")]
        System.Threading.Tasks.Task<string> CommandOutputAsync(string commandText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCF_cmdHelpServiceChannel : WebRole1.cmdHelperServiceReference.IWCF_cmdHelpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCF_cmdHelpServiceClient : System.ServiceModel.ClientBase<WebRole1.cmdHelperServiceReference.IWCF_cmdHelpService>, WebRole1.cmdHelperServiceReference.IWCF_cmdHelpService {
        
        public WCF_cmdHelpServiceClient() {
        }
        
        public WCF_cmdHelpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCF_cmdHelpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_cmdHelpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_cmdHelpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CommandOutput(string commandText) {
            return base.Channel.CommandOutput(commandText);
        }
        
        public System.Threading.Tasks.Task<string> CommandOutputAsync(string commandText) {
            return base.Channel.CommandOutputAsync(commandText);
        }
    }
}
